# Generated by Django 6.0.3 on 2026-03-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('espece', 'Espèces à la livraison')], max_length=50)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initié'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_interne', models.CharField(max_length=100, unique=True)),
                ('telephone_paiement', models.CharField(max_length=20)),
                ('operateur_response', models.JSONField(blank=True, default=dict)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_echec', models.DateTimeField(blank=True, null=True)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
