# Generated by Django 6.0.3 on 2026-03-21 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id_abonnement', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('basic', 'Basic - 10 000 FCFA/mois'), ('pro', 'Pro - 25 000 FCFA/mois'), ('premium', 'Premium - 50 000 FCFA/mois')], default='basic', max_length=50)),
                ('type_abo', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('impaye', 'Impayé'), ('annule', 'Annulé'), ('essai', "Période d'essai")], default='impaye', max_length=20)),
                ('paiement_auto', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'abonnements',
                'ordering': ['-date_debut'],
            },
        ),
    ]
