# Generated by Django 5.0.3 on 2026-03-21 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('theme', models.CharField(choices=[('default', 'Défaut'), ('moderne', 'Moderne'), ('minimaliste', 'Minimaliste'), ('colore', 'Coloré')], default='default', max_length=50)),
                ('couleur_primaire', models.CharField(default='#000000', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#FFFFFF', max_length=7)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'db_table': 'boutiques',
            },
        ),
    ]
